sudo: required

services:
  - docker

before_install:
  - docker build -t elliotbazuaye/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true elliotbazuaye/docker-react npm run test -- --coverage

before_deploy:
  - pip install --user awscli

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: docker-react
  env: Dockerreact-env
  bucket_name: elasticbeanstalk-us-east-1-042642202901
  bucket_path: docker-react
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
