sudo: required

services:
  - docker

before_install:
  - docker build elliotbazuaye/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true elliotbazuaye/docker-react npm run test -- --coverage --exit-code 0
