sudo: required

services:
  - docker

before_install:
  - docker build -t elliotbazuaye/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true elliotbazuaye/docker-react npm run test -- --coverage

before_deploy:
  - pip install --user awscli

deploy:
  provider: script
  script: bash deploy.sh
  skip_cleanup: true
  on:
    branch: main
